name: ASTRA Data Fetch

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Fetch ASTRA data and generate dashboard
      env:
        SHODAN_API_KEY: ${{ secrets.SHODAN_API_KEY }}
        GREYNOISE_API_KEY: ${{ secrets.GREYNOISE_API_KEY }}
        VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
      run: |
        python scripts/fetch_data.py
        
    - name: Commit and push updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "ASTRA Bot"
        git add data/ README.md
        git diff --staged --quiet || git commit -m "Update ASTRA data and dashboard - $(date)"
        git push
